# Generated by Django 3.2.2 on 2021-06-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('0', 'Perro'), ('1', 'Gato'), ('2', 'Otro')], max_length=1, verbose_name='Tipo')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('sexo', models.CharField(choices=[('0', 'Macho'), ('1', 'Hembra'), ('2', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nac')),
                ('observaciones', models.CharField(max_length=50, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
    ]
