# Generated by Django 3.0.5 on 2021-06-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('especie', models.TextField()),
                ('raza', models.TextField()),
                ('sexo', models.TextField()),
                ('esterilizado', models.BooleanField(default=False)),
                ('color', models.TextField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('observaciones', models.TextField()),
            ],
            options={
                'db_table': 'animales',
            },
        ),
    ]
