# Generated by Django 3.0.5 on 2021-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animales',
            options={'verbose_name': 'animales'},
        ),
        migrations.AlterField(
            model_name='animales',
            name='nombre',
            field=models.TextField(verbose_name='Nombre'),
        ),
    ]
