# Generated by Django 3.0.5 on 2021-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_auto_20210608_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animales',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterField(
            model_name='animales',
            name='nombre',
            field=models.TextField(),
        ),
    ]
