# Generated by Django 3.0.5 on 2021-06-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuidadores', '0001_initial'),
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosPlanAlimentacion',
            fields=[
                ('fecha', models.IntegerField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField()),
                ('id_cuidador', models.ForeignKey(db_column='id_cuidador', on_delete=django.db.models.deletion.DO_NOTHING, to='cuidadores.Cuidadores')),
                ('id_plan_alimentacion', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, to='animales.Animales')),
            ],
            options={
                'db_table': 'registros_plan_alimentacion',
            },
        ),
    ]
