# Generated by Django 3.0.5 on 2021-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidadores',
            fields=[
                ('id_cuidador', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'cuidadores',
            },
        ),
    ]
