# Generated by Django 3.0.5 on 2021-06-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuidadores',
            options={'verbose_name': 'Cuidador', 'verbose_name_plural': 'Cuidadores'},
        ),
    ]
