# Generated by Django 3.0.5 on 2021-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_auto_20210608_1109'),
        ('registros_peso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrospeso',
            name='fecha',
            field=models.IntegerField(db_column='fecha', primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='registrospeso',
            unique_together={('id_animal', 'fecha')},
        ),
    ]
