# Generated by Django 3.0.5 on 2021-06-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('id_tratamiento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.TextField()),
                ('id_animales', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, to='animales.Animales')),
            ],
            options={
                'db_table': 'tratamientos',
            },
        ),
    ]
